### PR TITLE
Added discovery function and icons. Also added listeners to control your tv with a keyboard.

### PR DESCRIPTION
**Pull request by Rldeckard**
Still need to find a power icon and get more of the icons from the original remote. Also need to fix the image so it stacks at the bottom instead of running the entire screen.

### CODE REVIEW

**Comment by donuts-are-good** [comment]
Wow thanks! I'm going to give it a build and see how it goes.

**Comment by donuts-are-good** [comment]
Two things I notice that might need addressing on my end:

- *.exe should be added to the .gitignore (oversight on my part, since I'm not on windows)

- I get a compile error for index out of range, I'm going to do some debugging to see if it is just how I'm building it (as a fyne app) since I'm just doing `go build` to build it.


```
dh@/Users/dh/temp/roku-fyne » ls
total 96096
drwxr-xr-x  13 dh  staff   416B Aug 31 22:14 .
drwxr-xr-x   3 dh  staff    96B Aug 31 22:14 ..
drwxr-xr-x  12 dh  staff   384B Aug 31 22:14 .git
-rw-r--r--   1 dh  staff    39B Aug 31 22:14 .gitignore
-rw-r--r--   1 dh  staff   1.0K Aug 31 22:14 LICENSE.md
-rw-r--r--   1 dh  staff   1.4K Aug 31 22:14 README.md
-rw-r--r--   1 dh  staff    15K Aug 31 22:14 bg.png
-rw-r--r--   1 dh  staff   1.7K Aug 31 22:14 go.mod
-rw-r--r--   1 dh  staff    66K Aug 31 22:14 go.sum
-rw-r--r--   1 dh  staff    68K Aug 31 22:14 icon.jpg
-rw-r--r--   1 dh  staff   5.1K Aug 31 22:14 main.go
-rwxr-xr-x   1 dh  staff    17M Aug 31 22:14 roku-fyne
-rw-r--r--   1 dh  staff    30M Aug 31 22:14 roku-fyne.exe

23-08-31 10:14PM
dh@/Users/dh/temp/roku-fyne » ./roku-fyne 
panic: runtime error: index out of range [0] with length 0

goroutine 19 [running]:
main.getRoku(0xc8)
	/Users/dh/temp/roku-fyne/main.go:59 +0x48c
created by main.main in goroutine 1
	/Users/dh/temp/roku-fyne/main.go:68 +0x2c


```

**Comment by donuts-are-good** [comment]
The icons look really good!! I resolved the index out of range by adding this to the wait command for the waitgroup.

```
wg.Wait()
if len(rokuList) > 0 {
    dropdown.Options = rokuList
    dropdown.SetSelected(rokuList[0])
} else {
    dropdown.Options = []string{"No Rokus found"}
    dropdown.SetSelected("No Rokus found")
}

```


However, it does not find my roku. If you can maintain the ability to provide the IP manually somehow when no rokus are found, that would benefit folks in this situation. 

Really cool that you found this project and want to contribute, I'm interested in hearing how you stumbled upon it. Thank you for adding the icons, it was something I wanted, actually both features are something I wanted, but just didn't get time to implement and probably would have done it otherwise.

**Comment by donuts-are-good** [comment]
This is what I have currently, if it is useful to you


```
package main

import (
	"fmt"
	"net"
	"net/http"
	"strings"
	"sync"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

func getRoku(ScanTime int) {
	var rokuList []string
	var m sync.Mutex
	conn, err := net.Dial("udp", "8.8.8.8:80")
	if err != nil {
		fmt.Println(err)
	}
	defer conn.Close()
	oct := strings.Split(conn.LocalAddr().String(), ".")
	client := http.Client{
		Timeout: time.Duration(ScanTime) * time.Millisecond,
	}
	//widget.NewSelect(rokuList, func(value string) {})
	var wg sync.WaitGroup
	for i := 1; i <= 254; i++ {
		wg.Add(1)
		host := fmt.Sprintf("%v.%v.%v.%v", oct[0], oct[1], oct[2], i)
		go func(ip string) {
			defer wg.Done()
			url := "http://" + ip + ":8060/query/device-info"
			resp, err := client.Get(url)
			if err != nil {
				if strings.Contains(err.Error(), "Client.Timeout exceeded") {
					return
				}
				dialog.NewError(err, w)
			}
			if resp.StatusCode == 200 {
				m.Lock()
				rokuList = append(rokuList, host)
				m.Unlock()
			}
			resp.Body.Close()
		}(host)

	}
	wg.Wait()
	if len(rokuList) > 0 {
		dropdown.Options = rokuList
		dropdown.SetSelected(rokuList[0])
	} else {
		dropdown.Options = []string{"No Rokus found"}
		dropdown.SetSelected("No Rokus found")
	}

}

var w fyne.Window
var ipEntry string
var dropdown *widget.Select

func main() {
	//start looking for Roku TVs on the local network.
	go getRoku(200)
	// Create a new Fyne application
	a := app.New()
	w = a.NewWindow("Roku")
	w.Resize(fyne.NewSize(225, 350))
	rokuImage := canvas.NewImageFromFile("bg.png")
	rokuImage.FillMode = canvas.ImageFillContain
	// Input field for Roku IP address. Fields defined in getRoku()
	dropdown = widget.NewSelect([]string{}, func(ipAddr string) {
		ipEntry = ipAddr
	})
	// Define a function that sends a keypress command to the Roku
	sendCommand := func(key string) {
		url := "http://" + ipEntry + ":8060/keypress/" + key
		resp, err := http.Post(url, "application/x-www-form-urlencoded", nil)
		if err != nil {
			println("Error:", err.Error())
			return
		}
		resp.Body.Close()
	}
	// Create buttons for each Roku command

	powerOnBtn := widget.NewButton("On", func() { sendCommand("PowerOn") })
	powerOffBtn := widget.NewButton("Off", func() { sendCommand("PowerOff") })
	backBtn := widget.NewButtonWithIcon("", theme.MailReplyIcon(), func() { sendCommand("Back") })
	homeBtn := widget.NewButtonWithIcon("", theme.HomeIcon(), func() { sendCommand("Home") })
	upBtn := widget.NewButtonWithIcon("", theme.MoveUpIcon(), func() { sendCommand("Up") })
	downBtn := widget.NewButtonWithIcon("", theme.MoveDownIcon(), func() { sendCommand("Down") })
	leftBtn := widget.NewButtonWithIcon("", theme.NavigateBackIcon(), func() { sendCommand("Left") })
	rightBtn := widget.NewButtonWithIcon("", theme.NavigateNextIcon(), func() { sendCommand("Right") })
	selectBtn := widget.NewButton("OK", func() { sendCommand("Select") })
	optionBtn := widget.NewButtonWithIcon("", theme.SettingsIcon(), func() { sendCommand("Info") })
	vDownBtn := widget.NewButtonWithIcon("", theme.VolumeDownIcon(), func() { sendCommand("VolumeDown") })
	vUpBtn := widget.NewButtonWithIcon("", theme.VolumeUpIcon(), func() { sendCommand("VolumeUP") })

	// Create layout and add buttons
	controls := container.NewVBox(
		dropdown,
		container.NewGridWithColumns(2, powerOffBtn, powerOnBtn),
		container.NewGridWithColumns(3,
			container.NewMax(backBtn), container.NewMax(optionBtn), container.NewMax(homeBtn),
			widget.NewLabel(""), container.NewMax(upBtn), widget.NewLabel(""),
			container.NewMax(leftBtn), container.NewMax(selectBtn), container.NewMax(rightBtn),
			container.NewMax(vDownBtn), container.NewMax(downBtn), container.NewMax(vUpBtn),
		),
		//Empty label required to get image to play nice
		container.NewGridWithRows(2, widget.NewLabel(""), rokuImage),
	)

	// Add the background and the controls to the window content
	w.SetContent(container.New(layout.NewMaxLayout(), controls))

	// Create a new window for the "About" section
	aboutWindow := a.NewWindow("About")
	aboutWindow.SetContent(widget.NewLabel("This is a simple Roku remote application."))
	aboutWindow.Resize(fyne.NewSize(300, 200))

	// Create a menu
	mainMenu := fyne.NewMainMenu(
		// A quit item will be appended to our first menu
		fyne.NewMenu("File",
			fyne.NewMenuItem("Add TV", func() {
				dialog.NewEntryDialog("Add TV", "IP", func(IPAddr string) {
					dropdown.Options = append(dropdown.Options, IPAddr)
				}, w).Show()
			}),
			fyne.NewMenuItem("Scan for Roku", func() {
				dropdown.Options = []string{"Please Wait..."}
				dropdown.SetSelectedIndex(0)
				dropdown.Refresh()
				getRoku(500)
			}),
			fyne.NewMenuItem("Quit", func() { a.Quit() }),
		),
		fyne.NewMenu("Help", fyne.NewMenuItem("About", func() {
			aboutWindow.Show()
		})),
	)
	w.Canvas().SetOnTypedKey(func(k *fyne.KeyEvent) {
		switch k.Name {
		case fyne.KeyLeft:
			sendCommand("Left")
		case fyne.KeyRight:
			sendCommand("Right")
		case fyne.KeySpace:
			sendCommand("Select")
		case fyne.KeyUp:
			sendCommand("Up")
		case fyne.KeyDown:
			sendCommand("Down")
		case fyne.KeyBackspace:
			sendCommand("Back")
		case "Return":
			sendCommand("Select")
		}

	})
	w.SetMainMenu(mainMenu)
	// Show and run the application
	w.ShowAndRun()

}

```

**Comment by Rldeckard** [comment]
Ah ya I figured not checking the index was going to come back to bite me, but I had way too much confidence in that scanning function. It is kind of weird that it didn't find your Rokus though. 

You're definitely right about the user experience of having an empty dropdown menu, but I added an Add TV menu option and a Scan for Ruku menu option if nothing was found. Maybe I just need a placeholder to say that, or an OnChanged event so you can add a TV in the dropdown menu.

Oh the subject of how I found you though, Fyne has a list of applications that were written with their library on their website so I stumbled across this while I was learning how to use Fyne and was just sucked in. I tried to make this application a few months ago, but I'm terrible with APIs so I couldn't get the queries to do anything to my TV. I'm dedicated to the Roku app, but it's becoming increasingly slow and it always shows my TVs as offline. Your application just works and has already taken over as my primary. 



If you have some time would you be able to print out the IP that the scanner grabs to see what it is? I'm thinking that's where the problem might be. I'll probably need to add a check if the local IP comes up empty.
`
getRoku(ScanTime int) {
    ...
    Println(conn.LocalAddr().String())
}
`

**Comment by Rldeckard** [comment]
You should be able to see my newest changes now in my most recent commit. I realized while reviewing that I was using the wrong dropdown function so the index issue should have never existed in the first place. After resolving that I added the option to manually add TVs in a more direct manor. Check it out and let me know if it's working for you.

**Comment by donuts-are-good** [comment]
Ah cool thanks! I pulled in the most recent changes, and added two log statements here:

```

func getRoku(ScanTime int) {
	//can't define the Add TV option here or the discovred IPs will mess up the dropdown
	var rokuList []string
	var m sync.Mutex
	conn, err := net.Dial("udp", "8.8.8.8:80")
	if err != nil {
		fmt.Println(err)
	}
	defer conn.Close()
	oct := strings.Split(conn.LocalAddr().String(), ".")
	client := http.Client{
		Timeout: time.Duration(ScanTime) * time.Millisecond,
	}
	//widget.NewSelect(rokuList, func(value string) {})
	var wg sync.WaitGroup
	for i := 1; i <= 254; i++ {
		wg.Add(1)
		host := fmt.Sprintf("%v.%v.%v.%v", oct[0], oct[1], oct[2], i)
		log.Println("host: " + host)
		go func(ip string) {
			defer wg.Done()
			url := "http://" + ip + ":8060/query/device-info"
			resp, err := client.Get(url)
			if err != nil {
				if strings.Contains(err.Error(), "Client.Timeout exceeded") {
					return
				}
				dialog.NewError(err, w)
			}
			if resp.StatusCode == 200 {
				log.Println("roku found!!! ")
				m.Lock()
				rokuList = append(rokuList, host)
				m.Unlock()
			}
			resp.Body.Close()
		}(host)

	}
```


When I run that, it appears to be searching 10.137.90.* rather than 192.168.1.*. I ran that ip range through `ifconfig` and it appears that it's maybe grabbing the wrong interface to scan, because it's scanning a vpn interface (tun), and it should be using the primary wifi or ethernet interfaces. 


When I input an IP manually, the request comes out in the logs like this:

```
2023/09/01 17:00:01 host: 10.137.90.254
Error: parse "http://(Add TV):8060/keypress/Select": invalid character " " in host name
Error: parse "http://(Add TV):8060/keypress/Select": invalid character " " in host name

```

**Comment by donuts-are-good** [comment]
also, one a sidenote, did some buttons get removed from the interface? there's no longer the ffwd and rev and play/pause keys, and it appears they got replaced with volume keys. can you tell me more about that?

**Comment by Rldeckard** [comment]
Ok I got the Add TV issue fixed(hopefully). I did a little more research and updated the IP function as well, but it should be grabbing the interface it uses to communicate with the internet. If it's still not working we may need to add a menu item to manually specify the network to scan.

For the buttons though I made those changes before I decided I was going to push this back up to you. Those buttons are mostly redundant to the Left, Right and OK buttons and I've never used them, but I did need the volume buttons for one of my Roku TVs. I don't mind redoing the interface and adding those back on there though if you prefer them.

**Comment by donuts-are-good** [comment]
Cool thanks :) I'll give it a shot tomorrow when I'm back at it. This weekend we've been traveling around so I haven't had much time

**Comment by donuts-are-good** [comment]
I noticed you pushed a release, how's it going so far?

**Comment by Rldeckard** [comment]
> I noticed you pushed a release, how's it going so far?

How's the release going? It's not really a thing for me. I try to push packaged binaries for any code I have these days in case someone wants to try it out with a simple download, but it's nothing really exciting especially since I don't use github much and have no following. Makes it super easy to put it on one of my new devices though.

**Comment by donuts-are-good** [comment]
Cool, you want me to pull and review the PR?

**Comment by Rldeckard** [comment]
Now would be a good time to check it out. Just finished adding in another cool feature. I also forked your scoreboard repo as well if you want to check that one out!

**Comment by donuts-are-good** [comment]
Oh man that's awesome, thanks :) I'm working over the weekend, but can likely test and merge mondayish on this repo and can check out the goodies you have in store for the scoreboard. I appreciate your help with the remote, thank you!

**Review by donuts-are-good — APPROVED** [review]

**Comment by donuts-are-good** [comment]
@Rldeckard I had a chance to try it out today, and though it didn't scan my roku, it looks great and the code looks like it should work. I appreciate your addition to the project, thank you!

**Pull request merged**
